CREATE DATABASE user_db;
CREATE DATABASE product_db;
CREATE DATABASE order_db;

GRANT ALL PRIVILEGES ON DATABASE user_db TO admin;
GRANT ALL PRIVILEGES ON DATABASE product_db TO admin;
GRANT ALL PRIVILEGES ON DATABASE order_db TO admin;